#!/bin/bash

# Execute the notebook and convert to HTML (no code cells)
jupyter nbconvert provinceszipped.ipynb --execute --no-input --to html

# Create a directory for public files and move the HTML there
mkdir -p ./public
mv provinceszipped.html ./public/
